on:
  workflow_call:
    inputs:
      registry-url:
        description: 'Registry location'
        required: true
        type: string
      project:
        description: 'Project where the artifact is included'
        required: true
        type: string
      artifact:
        description: 'Artifact name in the registry'
        required: true
        type: string
      version:
        description: 'Artifact version'
        required: true
        type: string
      folder:
        description: 'Dockerimage folder'
        default: './'
        required: false
        type: string
    secrets:
      username:
        description: 'Registry username'
        required: true
        type: string
      password:
        description: 'Registry password'
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: [ self-hosted, platform ]
    steps:
      - name: ⚙️ Set up Docker Context for Buildx
        run: |
          docker context create builders
      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
      - name: ⬇️ Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://${{ input.registry-url }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: ✏️ ⬆️ Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ input.folder }}
          file: ${{ input.folder }}/Dockerfile
          push: true
          tags: ${{ input.registry-url }}/${{ input.project }}/${{ input.artifact }}:${{ input.artifact-version }}
