on:
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
      artifact:
        description: 'Artifact'
        required: true
        type: string
      artifact-version:
        description: 'Artifact version'
        required: true
        type: string
      folder:
        description: 'Project folder'
        default: './'
        required: false
        type: string

jobs:
  reusable_workflow_job:
    uses:
    with:
      registry-url: 'harbor.internal.shared.empathy.co/'
      project: ${{ input.project }}
      artifact: ${{ input.artifact }}
      artifact-version: ${{ input.artifact-version }}
      folder: ${{ input.folder }}
    secrets:
      username: ${{ secrets.HARBOR_USERNAME }}
      password: ${{ secrets.HARBOR_TOKEN }}
