on:
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
      artifact:
        description: 'Artifact'
        required: true
        type: string
      version:
        description: 'Artifact version'
        required: true
        type: string
      image-artifact:
        description: 'Image github artifact'
        default: ${{ name }}
        required: false
        type: string

jobs:
  docker-publish-harbor:
    uses: empathyco/platform-reusable-github-actions/.github/workflows/docker-publish.yml@main
    with:
      registry-url: 'harbor.internal.shared.empathy.co'
      project: ${{ inputs.project }}
      artifact: ${{ inputs.artifact }}
      version: ${{ inputs.version }}
      image-artifact: ${{ inputs.image-artifact }}
    secrets:
      username: ${{ secrets.HARBOR_USERNAME }}
      password: ${{ secrets.HARBOR_TOKEN }}
