on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to deploy'
        required: true
        type: string
      branch:
        description: 'Branch where the change will be applied'
        default: 'main'
        required: false
        type: string
      yaml-filepath:
        description: 'Path to the yaml file'
        required: true
        type: string
      yaml-filename:
        description: 'Yaml filename'
        required: true
        type: string
      yaml-version-path:
        description: 'Path to the image tag property in the yaml values file'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string
      project:
        description: 'Project where the artifact is included'
        required: true
        type: string

jobs:
  reusable_workflow_job:
    uses: empathyco/platform-reusable-github-actions/.github/workflows/helm-deploy.yml@main
    with:
      registry-url: 'harbor.internal.shared.empathy.co/'
      repository: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      yaml-filepath: ${{ inputs.yaml-filepath }}
      yaml-version-path: ${{ inputs.yaml-version-path }}
      version: ${{ inputs.version }}
      project: ${{ input.project }}
    secrets:
      repository-token: ${{ secrets.SUPPORT_TOKEN }}
      username: ${{ secrets.HARBOR_USERNAME }}
      password: ${{ secrets.HARBOR_TOKEN }}