on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to deploy'
        required: true
        type: string
      branch:
        description: 'Branch where the change will be applied'
        default: 'main'
        required: false
        type: string
      yaml-filepath:
        description: 'Path to the yaml file'
        required: true
        type: string
      is-chart:
        description: 'True if deploying a helm chart'
        default: false
        required: false
        type: string
      yaml-version-path:
        description: 'Yaml path where the version property is set'
        required: true
        type: string
      version:
        required: true
        type: string
      registry-url:
        description: 'Registry location'
        required: true
        type: string
      project:
        description: 'Project where the artifact is included'
        required: true
        type: string
    secrets:
      repository-token:
        description: 'Token to clone repository'
        required: true
      username:
        description: 'Registry username'
        required: true
      password:
        description: 'Registry password'
        required: true


jobs:
  helm-deploy:
    runs-on: [ self-hosted, platform ]
    steps:
      #- name: ⚙️ Setup yq
       # uses: frenck/action-setup-yq@v1
      - name: ⚙️ Setup arkade
        uses: alexellis/setup-arkade@v2
      - name: ⚙️ Install tools
        uses: alexellis/arkade-get@master
        with:
          helm: latest
          yq: latest
      - name: ⬇️ Checkout targeted repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.repository-token }}
          path: 'targeted-repository'
      - name: ✏️ Modify version
        run: |
          yq -i '${{ inputs.yaml-version-path }} = "${{ inputs.version }}"' 'targeted-repository/${{ inputs.yaml-filepath }}/${{ inputs.is-chart == 'true' && 'Chart.yaml' || 'values.yaml' }}'
      - name: ✏️ Update chart
        if: inputs.is-chart == 'true'
        run: |
          helm repo add --username ${{ secrets.username }} --password ${{ secrets.password }} empathy https://${{ inputs.registry-url }}/${{ inputs.project }}
          helm dep update 'targeted-repository/${{ inputs.yaml-filepath }}'
      - name: ⬆️ Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update ${{ inputs.yaml-filepath }} to version ${{ inputs.version }}'
          branch: main
          repository: 'targeted-repository'
