on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner for runs-on'
        type: string
        default: platform
      team:
        description: 'Team folder with the k6 scripts'
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.runner }}
    steps:
    - uses: actions/checkout@v3
    - uses: alexellis/setup-arkade@v2
    - uses: alexellis/arkade-get@master
      with:
        kubectl: latest
    - name: Copy k6 scripts to EFS volume
      run: |
        kubectl apply -f pod.yaml -n k6
        sleep 20
        kubectl cp ./${{ inputs.team }} k6-pvc-copy:/test/ --no-preserve=true -n k6
        sleep 10
        kubectl delete pod k6-pvc-copy -n k6
