on:
  workflow_call:
    inputs:
      folder:
        description: 'Helm chart folder'
        required: true
        type: string
      release-name:
        description: 'Release name'
        required: true
        type: string
      aws-account-id:
        description: 'AWS Account ID'
        required: true
        type: string
      role-to-assume:
        description: 'Role to assume'
        required: true
        type: string
      cluster-name:
        description: 'Cluster name'
        required: true
        type: string
      issue-number:
        description: 'PR number'
        required: true
        type: string
      repo:
        description: 'Repository name'
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: [self-hosted, platform]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          folder:
            - '${{ inputs.folder }}/${{ inputs.release-name }}/**'
        token: ${{ secrets.SUPPORT_TOKEN }}
    - uses: alexellis/setup-arkade@v2
      if: steps.filter.outputs.folder == 'true'
    - uses: alexellis/arkade-get@master
      if: steps.filter.outputs.folder == 'true'
      with:
        kubectl: v1.25.3
        helm: latest
    - name: Set k8s context
      if: steps.filter.outputs.folder == 'true'
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: $KUBECONFIG_SECRET
      env:
        KUBECONFIG_SECRET: ${{ secrets.KUBE_CONFIG_SHARED }}
    - name: Helm chart diff
      if: steps.filter.outputs.folder == 'true'
      run: |
        kubectl get svc
        echo "\`\`\`diff" >> diff.txt
        helm template ${{ inputs.release-name }} ./${{ inputs.folder }}/${{ inputs.release-name }} | kubectl diff --show-managed-fields=false -f - 2>&1 >> diff.txt || true
        echo "\`\`\`" >> diff.txt
    - uses: actions/github-script@v6
      if: steps.filter.outputs.folder == 'true'
      with:
        github-token: ${{ secrets.SUPPORT_TOKEN }}
        script: |
          const fs = require('fs');
          github.rest.issues.createComment({
            issue_number: '${{ inputs.issue-number }}',
            owner: 'empathyco',
            repo: '${{ inputs.repo }}',
            body: fs.readFileSync('diff.txt', 'utf8')
          })
