on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner for runs-on'
        type: string
        default: platform
      folder:
        description: 'Helm chart folder'
        required: true
        type: string
      release-name:
        description: 'Release name'
        required: true
        type: string
      cluster:
        description: 'Cluster name'
        required: true
        type: string
      namespace:
        description: 'Namespace name'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      KUBECONFIG:
        required: false
jobs:
  k8s-diff:
    runs-on: ${{ inputs.runner }}
    steps:
    - uses: actions/checkout@v3
    - uses: alexellis/setup-arkade@v2
    - uses: alexellis/arkade-get@master
      with:
        kubectl: v1.25.3
        helm: latest
    - name: Set kubeconfig
      run: |
        mkdir -p ~/.kube
        echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config
        kubectl config --kubeconfig=$HOME/.kube/config use-context ${{ inputs.cluster }}
    - name: Helm chart diff
      run: |
        kubectl config set-context --current --namespace ${{ inputs.namespace }}
        helm template ${{ inputs.release-name }} ./${{ inputs.folder }}/${{ inputs.release-name }} | kubectl diff --show-managed-fields=false -f - 2>&1 >> diff-raw || true
        awk '/^- +labels\:$/ {n=NR+1;next}NR=n && /argocd\.argoproj\.io\/instance:/ {next}/argocd\.argoproj\.io\/instance:/ {next}{print}' diff-raw > diff
        awk 'BEGIN {a=0}/diff/{filename="diff-"a".txt"; a++}; {print >filename}' diff
        for i in $(ls -1 diff-*.txt); do
          changes=$(grep -cE "^[\-\+] +" $i || true)
          if [ $changes -eq 0 ]; then
            rm $i
          fi
        done
        count=$(ls -1 diff-*.txt 2>/dev/null | wc -l | awk '{print $1}')
        if [ ${count} -gt 0 ]; then
          echo "Ran Helm Diff for chart: \`${{ inputs.folder}}/${{ inputs.release-name}}\` in namespace: \`${{ inputs.namespace }}\`" >> diff.txt
          echo "<details><summary>Show Output</summary>" >> diff.txt
          echo "" >> diff.txt
          echo "\`\`\`diff" >> diff.txt
          cat diff-*.txt >> diff.txt
          echo "\`\`\`" >> diff.txt
          echo "</details>" >> diff.txt
          echo "" >> diff.txt
          echo "---" >> diff.txt
          echo "" >> diff.txt
          echo "<h1>:warning: <strong>Review this comment before merge!</strong> :warning:</h1>" >> diff.txt
        else 
          echo "No Helm Diff found for chart: \`${{ inputs.folder}}/${{ inputs.release-name}}\` in namespace: \`${{ inputs.namespace }}\`" >> diff.txt
        fi
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const fs = require('fs');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: fs.readFileSync('diff.txt', 'utf8')
          })
