on:
  workflow_call:
    inputs:
      folder:
        description: 'Helm chart folder'
        required: true
        type: string
      release-name:
        description: 'Release name'
        required: true
        type: string
      cluster:
        description: 'Cluster name'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: [self-hosted, platform]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          folder:
            - '${{ inputs.folder }}/${{ inputs.release-name }}/**'
        token: ${{ secrets.SUPPORT_TOKEN }}
    - uses: alexellis/setup-arkade@v2
      if: steps.filter.outputs.folder == 'true'
    - uses: alexellis/arkade-get@master
      if: steps.filter.outputs.folder == 'true'
      with:
        kubectl: v1.25.3
        helm: latest
    - name: Set kubeconfig shared cluster
      if: steps.filter.outputs.folder == 'true' && inputs.cluster == 'shared'
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG_SHARED }}
      run: |
        mkdir -p ~/.kube
        echo $KUBECONFIG > $HOME/.kube/config
    - name: Set kubeconfig test cluster
      if: steps.filter.outputs.folder == 'true' && inputs.cluster == 'test'
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG_TEST }}
      run: |
        mkdir -p ~/.kube
        echo $KUBECONFIG > $HOME/.kube/config
        cat $HOME/.kube/config
        kubectl use-context test
        kubectl get nodes
    - name: Helm chart diff
      if: steps.filter.outputs.folder == 'true'
      run: |
        echo "\`\`\`diff" >> diff.txt
        helm template ${{ inputs.release-name }} ./${{ inputs.folder }}/${{ inputs.release-name }} | kubectl diff --show-managed-fields=false -f - 2>&1 >> diff.txt || true
        echo "\`\`\`" >> diff.txt
    - uses: actions/github-script@v6
      if: steps.filter.outputs.folder == 'true'
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const fs = require('fs');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: fs.readFileSync('diff.txt', 'utf8')
          })
