on:
  workflow_call:
    inputs:
      folder:
        description: 'Helm chart folder'
        required: true
        type: string
      release-name:
        description: 'Release name'
        required: true
        type: string
      cluster:
        description: 'Cluster name'
        required: true
        type: string
      namespace:
        description: 'Namespace name'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      KUBECONFIG:
        required: false
jobs:
  reusable_workflow_job:
    runs-on: [self-hosted, platform]
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          folder:
            - '${{ inputs.folder }}/${{ inputs.release-name }}/**'
        token: ${{ secrets.SUPPORT_TOKEN }}
    - uses: alexellis/setup-arkade@v2
      if: steps.filter.outputs.folder == 'true'
    - uses: alexellis/arkade-get@master
      if: steps.filter.outputs.folder == 'true'
      with:
        kubectl: v1.25.3
        helm: latest
    - name: Set kubeconfig shared cluster
      if: steps.filter.outputs.folder == 'true' && inputs.cluster == 'shared'
      run: |
        mkdir -p ~/.kube
        echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config
        kubectl config --kubeconfig=$HOME/.kube/config use-context shared-services
    - name: Set kubeconfig test cluster
      if: steps.filter.outputs.folder == 'true' && inputs.cluster == 'test'
      run: |
        mkdir -p ~/.kube
        echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config
        kubectl config --kubeconfig=$HOME/.kube/config use-context test
    - name: Helm chart diff
      if: steps.filter.outputs.folder == 'true'
      run: |
        echo "<details><summary>Helm diff</summary>\n" >> diff.txt
        echo "\`\`\`diff" >> diff.txt
        helm template ${{ inputs.release-name }} ./${{ inputs.folder }}/${{ inputs.release-name }} | kubectl diff --show-managed-fields=false -f - -n ${{ inputs.namespace }} 2>&1 >> diff.txt || true
        echo "\`\`\`" >> diff.txt
        echo "</details>\n" >> diff.txt
        echo "---" >> diff.txt
        echo ":warning: Review this comment before merge!" >> diff.txt
    - uses: actions/github-script@v6
      if: steps.filter.outputs.folder == 'true'
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const fs = require('fs');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: fs.readFileSync('diff.txt', 'utf8')
          })
