on:
  workflow_call:
    # name: 'S3 + CloudFront'
    # description: 'Upload to Amazon S3 and invalidate CloudFront distribution'
    inputs:
      aws-account-id:
        description: 'AWS Account ID'
        required: true
        type: string
      s3-bucket-name:
        description: 'S3 Bucket Name'
        required: true
        type: string
      cloudfront-distribution-id:
        description: 'CloudFront Distribution ID'
        required: true
        type: string
      static-files-folder:
        description: 'Static files folder'
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: [self-hosted, platform]
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS credentials from Websites account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/GitHub-OIDC
        aws-region: us-east-1

    - name: Sync files to the bucket and invalidate CloudFront cache
      run: |
        aws s3 sync ${{ inputs.static-files-folder }} s3://${{ inputs.s3-bucket-name }} --delete --cache-control max-age=3600
        aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution-id }} --paths '/*'
