on:
  workflow_call:
    inputs:
      version-prefix:
        description: 'Prefix of version'
        default: ''
        required: false
        type:
      runner:
        description: 'Runner for runs-on'
        type: string
        default: platform
    outputs:
      version:
        description: 'Version obtained from tag'
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ${{ inputs.runner }}
    outputs:
      version: ${{ steps.version-step.outputs.version }}
    steps:
    - name: ⬇️Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ✏️➡️ Set Version
      id: version-step
      run: |
        echo version=$(git describe --tags --always --match ${{ inputs.version-prefix }}'*' | sed "s/^\(${{ inputs.version-prefix }}\)//") >> $GITHUB_OUTPUT
